// DIAGNOSTIC ONLY (not part of the project's tests). Corrected in the review session; see README.md "Script history".
//
// Applies one Stryker mutant from the ORIGINAL mutation.json to a disposable copy, runs the ordinary Vitest
// suite (forks pool, working time zones) and restores the file. usage:
//   node probe.mjs <workerDir> <project> <outFile> <id,id,...|base> [tz]
// ("base" runs the unmutated copy.)  Optional env: PROBE_FILES (space-separated test paths), PROBE_TIMEOUT (ms),
//   PROBE_EXPECT_TOTAL (tests expected in the run; default 778 when PROBE_FILES is not set), PROBE_LOG (log prefix).
//
// Each output line has a `verdict`:
//   caught      at least one test failed, or a suite could not load, in a fresh result file
//   not-caught  exit 0, a fresh readable result file, the expected number of tests, none failed
//   timeout     Vitest was killed by the time limit (never a pass)
//   invalid     anything else: spawn error, signal, missing/empty/unreadable result file, parse error,
//               non-zero exit with no failure recorded, or a test count that is not the expected one
// The ordinary suite excludes tests/diag/** (the diagnostic tests live there in a copy), so 778 is the project's own suite.
// Only `not-caught` means "the suite did not notice". `invalid` and `timeout` mean "no answer".
import { readFileSync, writeFileSync, appendFileSync, rmSync, existsSync, statSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'

const [workerDir, project, outFile, idList, tz] = process.argv.slice(2)
const report = JSON.parse(readFileSync(join(project, 'testing-and-qa/reports/mutation.json'), 'utf8'))
const byId = new Map()
for (const [file, fr] of Object.entries(report.files)) for (const m of fr.mutants) byId.set(String(m.id), { ...m, file })
const front = join(workerDir, 'frontend')
const resultPath = join(front, 'probe-result.json')
const expectTotal = process.env.PROBE_EXPECT_TOTAL ? Number(process.env.PROBE_EXPECT_TOTAL) : process.env.PROBE_FILES ? null : 778

function offset(text, line, col) {
  let o = 0
  for (let l = 1; l < line; l++) o = text.indexOf('\n', o) + 1
  return o + col - 1
}

for (const id of idList.split(',')) {
  const record = { id: id === 'base' ? 'base' : Number(id), tz: tz ?? 'default' }
  let path = null
  let original = null
  try {
    if (id !== 'base') {
      const m = byId.get(id)
      if (!m) { appendFileSync(outFile, JSON.stringify({ ...record, verdict: 'invalid', reason: 'unknown mutant id' }) + '\n'); continue }
      record.status = m.status
      record.file = m.file
      path = join(front, m.file)
      original = readFileSync(path, 'utf8')
      const crlf = original.includes('\r\n')
      const text = original.replace(/\r\n/g, '\n')
      const mutated = text.slice(0, offset(text, m.location.start.line, m.location.start.column)) + m.replacement + text.slice(offset(text, m.location.end.line, m.location.end.column))
      writeFileSync(path, crlf ? mutated.replace(/\n/g, '\r\n') : mutated)
    }

    // No stale result may survive into this run.
    rmSync(resultPath, { force: true })
    if (existsSync(resultPath)) { appendFileSync(outFile, JSON.stringify({ ...record, verdict: 'invalid', reason: 'could not remove the previous result file' }) + '\n'); continue }

    const env = { ...process.env }
    if (tz) env.TZ = tz
    const args = ['node_modules/vitest/vitest.mjs', 'run', ...(process.env.PROBE_FILES ? process.env.PROBE_FILES.split(' ') : []), '--exclude', 'tests/diag/**', '--exclude', '**/.stryker-tmp/**', '--reporter=json', '--outputFile=probe-result.json']
    const started = Date.now()
    const res = spawnSync(process.execPath, args, { cwd: front, env, encoding: 'utf8', timeout: Number(process.env.PROBE_TIMEOUT ?? 180000) })
    record.exit = res.status
    record.signal = res.signal
    record.spawnError = res.error ? String(res.error.code ?? res.error.message) : null
    record.seconds = Math.round((Date.now() - started) / 1000)
    if (process.env.PROBE_LOG) writeFileSync(`${process.env.PROBE_LOG}-${id}.txt`, `signal=${res.signal} status=${res.status}\n` + ((res.stdout ?? '') + (res.stderr ?? '')).slice(-3000))

    // Read the result generated by THIS run only.
    let total = null, passed = null, parseError = null
    const failed = []
    let suiteFailures = 0
    if (!existsSync(resultPath)) parseError = 'result file missing after the run'
    else if (statSync(resultPath).size === 0) parseError = 'result file empty after the run'
    else {
      try {
        const j = JSON.parse(readFileSync(resultPath, 'utf8'))
        total = j.numTotalTests
        passed = j.numPassedTests
        for (const f of j.testResults) {
          for (const a of f.assertionResults) if (a.status === 'failed') failed.push(`${f.name.replace(/\\/g, '/').split('/frontend/')[1]} > ${a.fullName}`)
          if (f.status === 'failed' && f.assertionResults.length === 0) { suiteFailures += 1; failed.push('SUITE-LEVEL FAILURE: ' + f.name.replace(/\\/g, '/').split('/frontend/')[1]) }
        }
      } catch (e) { parseError = String(e) }
    }
    Object.assign(record, { total, passed, failedCount: failed.length, suiteFailures, failed: failed.slice(0, 8), parseError })

    let verdict
    if (record.spawnError === 'ETIMEDOUT') verdict = 'timeout'
    else if (record.spawnError || record.signal) verdict = 'invalid'
    else if (parseError) verdict = 'invalid'
    else if (failed.length > 0) verdict = 'caught'
    else if (record.exit === 0 && (expectTotal === null || total === expectTotal)) verdict = 'not-caught'
    else verdict = 'invalid'
    record.verdict = verdict
    if (verdict === 'invalid' && !parseError && !record.spawnError && !record.signal) record.reason = `exit ${record.exit}, ${total} tests (expected ${expectTotal}), none failed`
    appendFileSync(outFile, JSON.stringify(record) + '\n')
  } finally {
    if (path !== null && original !== null) {
      writeFileSync(path, original)
      if (readFileSync(path, 'utf8') !== original) appendFileSync(outFile, JSON.stringify({ id: record.id, verdict: 'invalid', reason: 'FILE NOT RESTORED' }) + '\n')
    }
  }
}
